# Generated by Django 2.1.7 on 2019-04-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='noskhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.CharField(max_length=200, null=True)),
                ('tarik', models.CharField(max_length=200, null=True)),
                ('tari', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
