# Generated by Django 2.1.7 on 2019-04-07 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drug', '0002_noskhe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NationalCode', models.IntegerField(default=0)),
                ('FirstName', models.CharField(max_length=100, null=True)),
                ('LasttName', models.CharField(max_length=100, null=True)),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('Birthdate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicalCode', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescription_Date', models.DateField(auto_now=True)),
                ('Validity_Date', models.DateField(auto_now=True)),
                ('Deliver_Date', models.DateField(auto_now=True)),
                ('Prescription_Type', models.CharField(max_length=100)),
                ('Insurance', models.CharField(max_length=100)),
                ('Serial', models.IntegerField(default=0)),
                ('Page', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Patient')),
                ('physician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Physician')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField(default=0)),
                ('InsurancePrice', models.IntegerField(default=0)),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Prescription')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='noskhe',
        ),
    ]
